name: Update weather data

on:
  schedule:
    - cron: "0 * * * *"   # hourly
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: weather-dashboard-main
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed for rebase

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Fetch weather data
        run: python scripts/data_fetcher.py

      - name: Copy data to public directory
        run: |
          mkdir -p public
          cp data/*.json public/

      - name: Configure Git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes if any
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update weather data - $(date -u +'%Y-%m-%d %H:%M:%S') UTC"

      - name: Rebase on latest main
        run: |
          git fetch origin main
          git pull --rebase origin main

      - name: Push with lease
        run: git push --force-with-lease origin HEAD:main
